### ISSUE TITLE
Additional Next Acquisition Date Information

### ISSUE THREAD

**Issue by calvpang** [AustralianSDAF/EoAF#3]
![image](https://github.com/AustralianSDAF/EoAF/assets/63703885/3510f526-ab4c-4d2a-b064-3b4961222a9d)

Request:
User request for additional information regarding the next acquisition date.
Suggests adding "... in X days".

Potential Solution:

- Calculate the difference between the last acquisition date and estimate acquisition date.

Potential Issues:

- Calculated next acquisition date could fall to a date in the past. In that case, it is likely the satellite imagery has not yet been processed.

**Comment by catchSheep** [comment]
Fixed by e0c89e6d468156bbe7f3177e514439b131c1f575
