### ISSUE TITLE
Additional Information for Visualisation Options

### ISSUE THREAD

**Issue by calvpang** [AustralianSDAF/EoAF#6]
![image](https://github.com/AustralianSDAF/EoAF/assets/63703885/054939c8-402a-4b40-9e53-0e5d7c28a7cc)

Request:
User requests for additional explanatory texts regarding the visualisation options (Affects both Jupyter Notebooks & Gradio WebUI).

Potential Solutions:

1. Modify text from "Apply downscaling to products?" to "Apply a downscaling factor to reduce the spatial resolution of product for rapid display?"
2. Pictures showing the different colormaps alongside the radio buttons.
3. Modify text from "User percentiles for the colormap?" to "Apply percentiles to potentially enhance contrast and improve image display?"

**Comment by calvpang** [comment]
Addressed 1 & 3 for: 

- sentinel_2.ipynb
- landsat.ipynb
- viirs.ipynb
- sentinel_ui.py
- landsat_ui.py
- viirs_ui.py

**Comment by catchSheep** [comment]
Fixed by 0574ca1e3909e6b1868418603a40a13359a9456e and 9fe68418e1e44a2bfb366cae82a772a825dbebe8
